CREATE DATABASE db_automacoes

CREATE TABLE TB_STATUS_LOTE_LINHA (
IDSTATUS INT NOT NULL PRIMARY KEY IDENTITY(1,1),
DESCRICAO VARCHAR(255)
)

INSERT INTO TB_STATUS_LOTE_LINHA VALUES
('PENDENTE'),
('PROCESSANDO'),
('ERRO'),
('CONCLUÍDO')


CREATE TABLE TB_LOTE (
IDLOTE INT NOT NULL PRIMARY KEY IDENTITY(1,1),
NOME_CARGA VARCHAR(255),
DATACAD DATETIME
)

CREATE TABLE TB_LOTE_LINHA (
IDLINHA INT NOT NULL PRIMARY KEY IDENTITY(1,1),
IDLOTE INT NOT NULL FOREIGN KEY REFERENCES TB_LOTE(IDLOTE),
IDSTATUS INT NOT NULL FOREIGN KEY REFERENCES TB_STATUS_LOTE_LINHA(IDSTATUS),
DATACAD DATETIME,
DATA_INICIO_PROCESSAMENTO DATETIME,
DATA_FIM_PROCESSAMENTO DATETIME,
tlog varchar(max)
)





CREATE TABLE STF.TB_BUSCA_JURISPRUDENCIA (
IDBUSCA INT NOT NULL PRIMARY KEY IDENTITY(1,1),
PALAVRA_CHAVE VARCHAR(2000) NOT NULL,
DATACAD DATETIME,
total int
)

CREATE TABLE STF.TB_RETORNO_JURISPRUDENCIA(
IDRETORNO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
IDBUSCA INT NOT NULL FOREIGN KEY REFERENCES STF.TB_BUSCA_JURISPRUDENCIA(IDBUSCA),
DATACAD DATETIME NOT NULL,
DECISAO VARCHAR(MAX),
EMENTA VARCHAR(MAX),
DATA_PUBLICACAO VARCHAR(15),
TEMA VARCHAR(MAX),
TESE VARCHAR(MAX),
DATA_JULGAMENTO VARCHAR(15),
CLASSE_PROCESSUAL VARCHAR(500),
DOUTRINA VARCHAR(MAX),
RELATOR VARCHAR(500),
legislacao varchar(max)
)



CREATE TABLE STF.TB_RETORNO_JURISPRUDENCIA_PARTES (
id int not null identity(1,1) primary key,
datacad datetime,
tipo varchar(255),
nome varchar(2000),
id_tb_jurisprudencia int not null foreign key references STF.TB_RETORNO_JURISPRUDENCIA(IDRETORNO)

)



